set(ALICE_LRI_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/src/includeimpl/Core.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/utils/logger/Logger.h
        ${CMAKE_CURRENT_LIST_DIR}/src/utils/Timer.h
        ${CMAKE_CURRENT_LIST_DIR}/src/point/PointUtils.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/point/PointUtils.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/VerticalIntrinsicsEstimator.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/VerticalIntrinsicsEstimator.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/IntrinsicsEstimator.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/IntrinsicsEstimator.h
        ${CMAKE_CURRENT_LIST_DIR}/src/hough/HoughTransform.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/hough/HoughTransform.h
        ${CMAKE_CURRENT_LIST_DIR}/src/hash/HashUtils.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/hash/HashUtils.h
        ${CMAKE_CURRENT_LIST_DIR}/src/point/PointArray.h
        ${CMAKE_CURRENT_LIST_DIR}/src/point/PointArray.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/utils/Utils.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/helper/VerticalLogging.h
        ${CMAKE_CURRENT_LIST_DIR}/src/utils/json/JsonConverters.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/utils/json/JsonConverters.h
        ${CMAKE_CURRENT_LIST_DIR}/src/math/Stats.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/math/Stats.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/conflict/ScanlineConflictSolver.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/conflict/ScanlineConflictSolver.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/pool/VerticalScanlinePool.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/pool/VerticalScanlinePool.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/HorizontalScanlineArray.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/HorizontalScanlineArray.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/HorizontalMath.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/HorizontalMath.h
        ${CMAKE_CURRENT_LIST_DIR}/include/alice_lri/Structs.hpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/HorizontalIntrinsicsEstimator.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/HorizontalIntrinsicsEstimator.h
        ${CMAKE_CURRENT_LIST_DIR}/src/rangeimage/RangeImageUtils.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/rangeimage/RangeImageUtils.h
        ${CMAKE_CURRENT_LIST_DIR}/src/Constants.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/SegmentedMedianLinearRegressor.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/SegmentedMedianLinearRegressor.h
        ${CMAKE_CURRENT_LIST_DIR}/src/includeimpl/Structs.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalScanlineLimits.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalScanlineLimits.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalScanlineEstimator.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalScanlineEstimator.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/PeriodicFitter.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/helper/PeriodicFitter.h
        ${CMAKE_CURRENT_LIST_DIR}/src/math/Trigonometry.h
        ${CMAKE_CURRENT_LIST_DIR}/src/math/Trigonometry.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalHeuristicsEstimator.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalHeuristicsEstimator.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/estimation/VerticalScanlineEstimationStructs.h
        ${CMAKE_CURRENT_LIST_DIR}/src/utils/logger/LoggingOverrides.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/conflict/ScanlineConflictStructs.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/VerticalIntrinsicsStructs.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/horizontal/HorizontalIntrinsicsStructs.h
        ${CMAKE_CURRENT_LIST_DIR}/src/hough/HoughStructs.h
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/conflict/ScanlineConflictEvaluator.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/intrinsics/vertical/conflict/ScanlineConflictEvaluator.h
        ${CMAKE_CURRENT_LIST_DIR}/src/math/LinearRegressor.cpp
        ${CMAKE_CURRENT_LIST_DIR}/src/math/LinearRegressor.h
        ${CMAKE_CURRENT_LIST_DIR}/src/includeimpl/util/AliceString.cpp
        ${CMAKE_CURRENT_LIST_DIR}/include/alice_lri/ApiGuards.hpp
        ${CMAKE_CURRENT_LIST_DIR}/include/alice_lri/Result.hpp
        ${CMAKE_CURRENT_LIST_DIR}/include/alice_lri/util/AliceString.hpp
        ${CMAKE_CURRENT_LIST_DIR}/include/alice_lri/util/AliceArray.hpp
        ${CMAKE_CURRENT_LIST_DIR}/src/includeimpl/Result.cpp
)
