name: build-documentation
author: samuelss1996
description: Build documentation using Sphinx and Doxygen
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Conan
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install 'conan>=2.0'
        conan profile detect --force

    - name: Install Python package and generate stubs
      shell: bash
      run: |
        cd python
        ./install_dev_and_stubs.sh

    - name: Install documentation dependencies
      shell: bash
      run: |
        pip install -r docs/requirements.txt
        sudo apt-get update && sudo apt-get install -y doxygen

    - name: Build Doxygen XML
      shell: bash
      run: |
        cd docs
        doxygen Doxyfile

    - name: Build Sphinx HTML
      shell: bash
      run: |
        cd docs
        sphinx-build -b html . _build/html
