name: Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build-and-attach:
    if: github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Tag Version: $VERSION"

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_i686"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BEFORE_BUILD: "pip install conan && conan profile detect"
        with:
          package-dir: './python'

      - name: Upload wheels as workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          retention-days: 7

      - name: Create C++ tarball
        shell: bash
        run: |
          CPP_TARBALL_NAME="alice-lri-${{ env.VERSION }}-cpp-lib.tar.gz"
          tar -czf "$CPP_TARBALL_NAME" -C lib . 
          echo "CPP_TARBALL_PATH=$CPP_TARBALL_NAME" >> $GITHUB_ENV

      - name: Create GitHub release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            wheelhouse/*.whl
            ${{ env.CPP_TARBALL_PATH }}

  publish-pypi:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist/

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
          
  deploy-documentation:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Deploy documentation
        uses: ./.github/actions/deploy-documentation
        